name: DeployPwt5ca
on:
  push:
    branches:
    - pwt5ca

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: .
        remote_path: /u/lab/pwt5ca/public_html/pwt5ca
        remote_host: portal.cs.virginia.edu
        remote_user: pwt5ca
        remote_key: ${{ secrets.DEPLOY_KEY }}
