on:
  push:
    branches: [main]

jobs:
  rsync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server; main
        uses: up9cloud/action-rsync@v1.1
        env:
          HOST: portal.cs.virginia.edu
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          TARGET: /u/lab/pwt5ca/public_html/main

          VERBOSE: true
          USER: pwt5ca
          SSH_ARGS: "-p 22 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
          ARGS: -avzr --exclude '.git*' --exclude '.gitignore' --exclude '*.md'
          SOURCE: ./

          PRE_SCRIPT: ""
          POST_SCRIPT: "chmod 0777 /u/lab/pwt5ca/public_html/pwt5ca/assets/img/downloaded"
