on: [push]
jobs:
  rsync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to server; pwt5ca
      uses: up9cloud/action-rsync@v1.1
      env:
        HOST: portal.cs.virginia.edu
        KEY: ${{secrets.DEPLOY_SSH_KEY}}
        TARGET: /u/lab/pwt5ca/public_html/pwt5ca

        VERBOSE: true
        USER: pwt5ca
        # PORT: 2222 # no need to set this, because of $SSH_ARGS
        ARGS: -avzr --exclude=/.git/
        SOURCE: .

        PRE_SCRIPT: |
          echo start at:
          date -u --rfc-3339=ns
        POST_SCRIPT: "echo done at: && date -u --rfc-3339=ns"